# Generated by Django 2.2.4 on 2022-01-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20220105_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
