# Generated by Django 2.2.4 on 2022-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_appointment_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pname_two',
            field=models.CharField(default='pet', max_length=20),
        ),
    ]
