# Generated by Django 2.2.4 on 2022-01-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_appointment_pname_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pname_two',
        ),
    ]
