# Generated by Django 2.2.4 on 2022-01-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_remove_appointment_pname_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_date',
        ),
    ]
