# Generated by Django 2.2.4 on 2022-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_remove_appointment_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.CharField(default='00/00/0000', max_length=10),
        ),
    ]
