# Generated by Django 2.2.4 on 2022-01-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_appointment_preferred_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(),
        ),
    ]
